# Основные системные настройки
mixed-port: 7890
allow-lan: false
tcp-concurrent: true
find-process-mode: off
global-client-fingerprint: random
log-level: error
ipv6: false
geodata-loader: standard
geo-auto-update: false

# DNS с нулевым доверием
dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  default-nameservers:
    - 77.88.8.8          # Яндекс (для поиска DoH-серверов)
    - 193.58.251.251     # SkyDNS
  proxy-server-nameserver:
    - https://8.8.8.8/dns-query # Для поиска узлов VLESS и GitHub
  nameserver:
    - https://dns.google/dns-query
    - https://cloudflare-dns.com/dns-query
    - https://9.9.9.9/dns-query

# Провайдер серверов (Склад)
proxy-providers:
  black-vless:
    type: http
    url: "https://raw.githubusercontent.com/mycum/ClashMetaForAndroid/refs/heads/main/proxy_lists/fixed_proxies.txt"
    interval: 10800 # Обновление списка раз в 3 часа
    path: ./providers/black_vless.yaml
    health-check:
      enable: true
      interval: 600   # Проверка раз в 10 минут
      lazy: true      # НЕ проверять, если VPN не используется (экономия)
      url: "https://api.telegram.org" # Строгая проверка доступности Telegram

# Автоматический выбор (Магазин)
proxy-groups:
  # 1. Тестируем пинг в фоне
  - name: "⚡ Авто-выбор"
    type: url-test
    hidden: true
    use:
      - black-vless
    url: "https://api.telegram.org" # Строгая проверка доступности Telegram
    interval: 300   # Перепроверять лучший сервер каждые 5 минут при работе
    tolerance: 150  # Не менять сервер, если разница в пинге меньше 150мс
    lazy: true      # Экономия: не тестировать узлы, пока нет трафика

  # 2. Главная витрина, которую видит пользователь
  - name: "AUTO-VPN"
    type: select
    proxies:
      - "⚡ Авто-выбор" # Эта кнопка всегда будет на первом месте
    use:
      - black-vless    # А под ней ручной список серверов

# Правила маршрутизации (Безопасность)
rules:
  # Защита локальной сети (DIRECT)
  - DOMAIN-SUFFIX,local,DIRECT
  - IP-CIDR,127.0.0.0/8,DIRECT,no-resolve
  - IP-CIDR,172.16.0.0/12,DIRECT,no-resolve
  - IP-CIDR,192.168.0.0/16,DIRECT,no-resolve
  - IP-CIDR,10.0.0.0/8,DIRECT,no-resolve
  - DOMAIN,raw.githubusercontent.com,⚡ Авто-выбор

  # Всё остальное - через автомат
  - MATCH, AUTO-VPN